feat(interception): set up udev rules
As noted in the comment, having this in here is a bit of an abuse, but
the alternatives suck in different ways too:

- Putting it in the "dotfiles" aspect: now we would need `sudo` to
  install dotfiles, and `udev` has nothing to do with dotfiles, really.
- Making a separate "udev" aspect: lots of overhead for a little thing;
  also, it relies on scripts installed in our home directory... maybe we
  should think about installing elsewhere, but still, pretending that
  this will ever be used by more than just `glh` is a joke.

So, here it goes. Note that I had to adjust the TS config because `tsc`
was choking on ".ts" (timestamp) files

    aspects/interception/support/CMakeFiles/mac2linux.dir/compiler_depend.ts:1:1 - error TS18016: Private identifiers are not allowed outside class bodies.

    1 # CMAKE generated file: DO NOT EDIT!

    (etc)