fix: try commit symlink change again
Parent commit was empty, and it is starting to feel like a jj bug, or
maybe I am holding it wrong.

    $ jj diff -r @ bin/crypt-status
    Regular file became symlink at bin/crypt-status:

Try squashing so I can force-push:

    $ jj squash -i -r @
    Error: Commit 23e29b9b15de is immutable
    Hint: Could not modify commit: twtqmoru 23e29b9b main | (empty) fix: turn regular file into a symlink
    Hint: Immutable commits are used to protect shared history.
    Hint: For more information, see:
          - https://jj-vcs.github.io/jj/latest/config/#set-of-immutable-commits
          - `jj help -k config`, "Set of immutable commits"
    Hint: This operation would rewrite 1 immutable commits.

Fair enough. Let's `sudo` it:

    $ jj squash -i -r @ --ignore-immutable
    Error: No changes selected

👆 that's the thing that feels like a bug. It lets me select the file in
the interactive view, but it won't create the commit.

So, trying again (in this commit) with:

    $ jj commit bin/crypt-status

which hopefully will work...