refactor(homebrew): replace "elinks" with "felinks"
Because:

    Error: elinks has been disabled because it No releases since 2012;
    consider using the maintained felinks instead!

Although note, I have no idea why I had both "links" and "elinks" in
there; it's been so long since I used either of them.