refactor(homebrew): switch from "blurred" to "hazeover"
Blurred is disabled in Homebrew:

> Disabled because it is now exclusively distributed on the Mac App
> Store! It was disabled on 2026-06-28.

Additionally, it hasn't been updated in 6 years and still requires
Rosetta, so seems doomed to stop working eventually. The developer is
still active on GitHub (eg. see https://github.com/dwarvesf/hidden) but
the repo (https://github.com/dwarvesf/blurred) now 404s; last snapshot
for it on web.archive.org looks to be from 2026-02-18:

- https://web.archive.org/web/20260218200817/https://github.com/dwarvesf/blurred

HazeOver is an alternative available via Homebrew, and vouched for by
the Gruber himself:

- https://daringfireball.net/2026/03/hazeover

Not free, but not expensive either (licenses are something like 5
bucks).

One gotcha to bear in mind. Had to install this with:

```
env HOMEBREW_CASK_OPTS= brew install --cask hazeover
```

because otherwise:

```
Error: hazeover: Cask 'hazeover' does not have a sha256 checksum defined and was not installed.
This means you have the --require-sha option set, perhaps in your `$HOMEBREW_CASK_OPTS`.
```

Change-Id: qqztvnlmpmxmooyoqopxyvqkltnxvlyx