fix(homebrew): catch up with breaking changes
3 packages failed to install:

    1.  camlp4 (removed)

            Error: No similarly named formulae found.
            Error: No available formula with the name "camlp4".
            ==> Searching for similarly named formulae...
            ==> Searching for a previously deleted formula (in the last month)...
            Error: No previously deleted formula found.
            ==> Searching taps on GitHub...
            Error: No formulae found in taps.

    2.  git (option removed, appears to be default now)

            Error: invalid option: --with-pcre

        Some talk here of it being named --with-pcre2 now, but
        I think it's just used by default now and that option
        doesn't exist either:

            https://stackoverflow.com/questions/22055390/how-to-install-git-with-pcre-support-on-macos-with-homebrew

    3.  gnu-sed (option removed)

            Error: invalid option: --with-default-names

        As mentioned here:

            https://stackoverflow.com/questions/30003570/how-to-use-gnu-sed-on-mac-os-10-10-brew-install-default-names-no-longer-su

        Note that there is no `--default-names` option,
        also mentioned in that thread.