chore: bump NodeJS version for CI
Should prevent errors like this one:

    Error: Invalid tag name "*.{md,ts}": Tags may not have any characters that encodeURIComponent encodes.

seen here:

    https://github.com/wincent/wincent/runs/7494981287?check_suite_focus=true

I think, as a result of the move from:

    npx prettier --check "**/*.{js,json,md,ts}" "*.{md,ts}"

to:

    npx -y prettier --check "**/*.{js,json,md,ts}" "*.{md,ts}"

As explained in `man npx`:

    Compatibility with Older npx Versions

    The npx binary was rewritten in npm v7.0.0, and the  standalone
    npx  package  deprecated  at  that time.  npx uses the npm exec
    command instead of  a  separate  argument  parser  and  install
    process,  with  some affordances to maintain backwards compati‐
    bility with the arguments it accepted in previous versions.

    This resulted in some shifts in its functionality:

    • To prevent security and user-experience problems from mistyp‐
      ing  package  names,  npx prompts before installing anything.
      Suppress this prompt with the -y or --yes option.

So, I guess with NodeJS v12 I get an older version of `npx`, and it
probably doesn't support the `-y` switch.

Go to v18 because that's what Fig itself is using now.