chore(nvim): don't install Solargraph
Because it is causing problems on codespaces now:

  ERROR:  Error installing solargraph:
      The last version of nokogiri (>= 0) to support your Ruby & RubyGems was 1.15.5. Try installing it with `gem install nokogiri -v 1.15.5` and then running the current command again
      nokogiri requires Ruby version >= 3.0, < 3.4.dev. The current ruby version is 2.7.0.0.