fix: update error handling for TypeScript 4.4
As explained here:

    https://devblogs.microsoft.com/typescript/announcing-typescript-4-4/

caught errors now have type `unknown` instead of `any`. Now, it's true
that sometimes I can be pretty sure that I'm going to get an `Error`
instance in these `catch` clauses, but I would rather just mindlessly
obey the type checker and adapt the code to handle any value. This
"future-proofs" the code by making it ready to handle any changes that
invalidate my initial assumptions here.

Fixes these post-upgrade errors:

    fig/readAspect.ts:32:24 - error TS2571: Object is of type 'unknown'.

    32     throw new Error(`${error.message} in ${directory}`);
                              ~~~~~

    fig/readProject.ts:15:24 - error TS2571: Object is of type 'unknown'.

    15     throw new Error(`${error.message} in ${path}`);
                              ~~~~~

    fig/test.ts:16:19 - error TS2345: Argument of type 'unknown' is not assignable to parameter of type 'string'.

    16         log.error(error);
                         ~~~~~

    fig/test/harness.ts:66:25 - error TS2571: Object is of type 'unknown'.

    66         const message = caught.toString();
                               ~~~~~~

    fig/test/harness.ts:153:16 - error TS2571: Object is of type 'unknown'.

    153       log(`\n${error.message}\n`);
                       ~~~~~