fix(fig): fix type errors
Since update of `@types/node` from 22.15.3 to 22.15.27, which brought in
three new overloads for `fs.readdirSync` via this PR:

- https://github.com/DefinitelyTyped/DefinitelyTyped/pull/72534

we get these errors from TypeScript:

```
fig/dsl/resource.ts:50:33 - error TS2345: Argument of type '{ withFileTypes: true; }' is not assignable to parameter of type '{ encoding: "buffer"; withFileTypes: true; recursive?: boolean | undefined; }'.
  Property 'encoding' is missing in type '{ withFileTypes: true; }' but required in type '{ encoding: "buffer"; withFileTypes: true; recursive?: boolean | undefined; }'.

50     return readdirSync(current, {withFileTypes: true})
                                   ~~~~~~~~~~~~~~~~~~~~~

  node_modules/@types/node/fs.d.ts:2204:13
    2204             encoding: "buffer";
                     ~~~~~~~~
    'encoding' is declared here.

fig/dsl/resource.ts:55:46 - error TS2345: Argument of type 'Buffer<ArrayBufferLike>' is not assignable to parameter of type 'string'.

55       .filter(({name}) => components[0].test(name))
                                                ~~~~

fig/dsl/resource.ts:56:16 - error TS2345: Argument of type '(entry: Dirent) => Path | Path[]' is not assignable to parameter of type '(this: undefined, value: Dirent<Buffer<ArrayBufferLike>>, index: number, array: Dirent<Buffer<ArrayBufferLike>>[]) => Path | readonly Path[]'.
  Types of parameters 'entry' and 'value' are incompatible.
    Type 'Dirent<Buffer<ArrayBufferLike>>' is not assignable to type 'Dirent<string>'.
      Type 'Buffer<ArrayBufferLike>' is not assignable to type 'string'.

56       .flatMap((entry: Dirent) => {
                  ~~~~~~~~~~~~~~~~~~~~
```

So, it's selecting one of the overloads with a required `encoding` key
in the options object instead of the overload that we want (the only one
with `withFileTypes: true`):

```
export function readdirSync(
    path: PathLike,
    options: ObjectEncodingOptions & {
        withFileTypes: true;
        recursive?: boolean | undefined;
    },
): Dirent[];
```

Sigh. Rather than trying to get our `Parameters` and `ReturnType`
helpers to extract the correct type, let's just code the only calling
pattern we actually care about directly (`resource.ts` is currently the
only call-site, and it calls our `readdirSync()` wrapper exactly once).