chore: update Node dependencies
Requires a tweak to fix a new type error:

    fig/getCallers.ts:22:15 - error TS2769: No overload matches this call.
      Overload 1 of 2, '(predicate: (value: string | undefined, index: number, array: (string | undefined)[]) => value is string, thisArg?: any): string[]', gave the following error.
        Argument of type '(element: string | null) => element is string' is not assignable to parameter of type '(value: string | undefined, index: number, array: (string | undefined)[]) => value is string'.
          Types of parameters 'element' and 'value' are incompatible.
            Type 'string | undefined' is not assignable to type 'string | null'.
              Type 'undefined' is not assignable to type 'string | null'.
      Overload 2 of 2, '(predicate: (value: string | undefined, index: number, array: (string | undefined)[]) => unknown, thisArg?: any): (string | undefined)[]', gave the following error.
        Argument of type '(element: string | null) => element is string' is not assignable to parameter of type '(value: string | undefined, index: number, array: (string | undefined)[]) => unknown'.
          Types of parameters 'element' and 'value' are incompatible.
            Type 'string | undefined' is not assignable to type 'string | null'.

    22       .filter(nonNull);
                     ~~~~~~~

which is kind of hard to read, but the root cause is that it seems
`getFileName()` can return `string | undefined` and I was treating it as
though it returned `string | null`. Either TypeScript has gotten better
at flow analysis, or the type definitions have changed. Either way, I
softened the code to handle both `null` and `undefined`.