fix(dotfiles): fix broken `gr` alias
Broken since 777559d6d572bedade30aec4a90714918b75e1f8
("refactor(dotfiles): rename `no_description_set()` to
`empty_description()`", 2026-02-26) because I forgot to update one
reference, leading to this error when running `jj gr` (or `jj o` etc):

    Error: Failed to parse revset: Function `no_description_set` doesn't exist
    Caused by:  --> 1:7
      |
    1 | ::@ & no_description_set()
      |       ^----------------^
      |
      = Function `no_description_set` doesn't exist

Change-Id: yltmnmzlzkvkposnqtxupxvsoszxvszp