Hammerspoon: fix console noise that started with v0.9.47
Been getting all manner of console spam since the upgrade a couple of days ago.
Many messages like:

  ERROR:   LuaSkin: hs.application.watcher callback error:
  ....app/Contents/Resources/extensions/hs/uielement/init.lua:187:
  bad argument #-2 to '_stop'
  (hs.uielement.watcher.userdata expected, got hs.uielement.watcher.userdata)

Nothing suspicious in the release notes. Switching to (the still "experimental")
`hs.window.filter` API allows me to avoid the code paths that were throwing off
the errors/warnings, and delete a lot of code to boot. Seems to work well. Yay.