refactor(pacman): move "gnome-icon-theme" into "aur" aspect
Because it is in the AUR now:

    error: target not found: gnome-icon-theme

See:

    https://aur.archlinux.org/packages/gnome-icon-theme