fix(codespaces): fix type errors
    error TS6133: 'skip' is declared but its value is never read.
    error TS6133: 'stat' is declared but its value is never